apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-api
spec:
  selector:
    matchLabels:
      app: consumer-api
  template:
    metadata:
      labels:
        app: consumer-api
    spec:
      containers:
      - name: consumer-api
        image: trekkerone/consumer-api
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-api
spec:
  type: NodePort
  selector:
    app: consumer-api
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 32600